# Generated by Django 4.1.7 on 2023-03-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uniprotData',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('sequence', models.TextField()),
                ('features', models.TextField()),
            ],
        ),
    ]
