# Generated by Django 4.1.7 on 2023-03-24 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prototypeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FeatureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acession_id', models.CharField(max_length=10, unique=True)),
                ('name', models.TextField()),
                ('sequence', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='uniprotData',
        ),
        migrations.AddField(
            model_name='feature',
            name='feature_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototypeApp.featuretype'),
        ),
        migrations.AddField(
            model_name='feature',
            name='protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototypeApp.protein'),
        ),
    ]
