# Generated by Django 4.1.7 on 2023-03-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototypeApp', '0002_feature_featuretype_protein_delete_uniprotdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuretype',
            name='value',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
